apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  # these lables are replicaset labls
  lables:
    project: roboshop
    purpose: rs-demo
    tier: frontend
    component: frontend
spec:
  replicas: 3
  selector:
    # using these lables replica set selects the pod 
    matchLabels:
      project: roboshop
      purpose: rs-demo
      tier: frontend
      component: frontend
  # this is pod defenition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        purpose: rs-demo
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx